<?php

namespace Test\AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {
    
    public function getAllTypes() {
        $qB = $this->createQueryBuilder('u')
                ->select('u.username');
        $qry = $qB->getQuery();
        $libellesType = array();
        foreach ($qry->getScalarResult() as $type) {
            $libellesType[] = $type['username'];
        }
        return $libellesType;
    }
}
